services:
  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: aluno123

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
  web:
    build:
      context: ./
      dockerfile: Dockerfile-Nginx
    ports:
      - "80:80"
    volumes:
      - ./meufrontend:/usr/share/nginx/html

  php-fpm:
    build:
      context: ./
      dockerfile: Dockerfile-Php8-Fpm
    container_name: fzl-php8.3-fpm
    volumes:
      - ./:/var/www/html